### ISSUE TITLE
BOM for Puck.js

### ISSUE THREAD

**Issue by robksawyer** [espruino/EspruinoBoard#8]
I'm working on a BOM for the Puck.js as I'd like to try to build one for fun. And if it's not too much to ask (probably is), could you take a look at https://octopart.com/bom-tool/4nxH00z7/swbUP1bhfnRI3VCJ and let me know how close I am? 🙏

**Comment by gfwilliams** [comment]
Hi - I'm afraid I don't have time to look through everything and make sure so you're buying at your own risk, but it looks roughly ok.

Looks like you added MMBFJ310 though - there's a part outline on the board to allow a SOT23 to be fitted to IO pins for whatever reason, but it's not populated (I guess there might be other parts that aren't fitted as well).

Worth noting that the tune capacitors for NFC will depend on the board you use, so will almost certainly be off - it's a bit of an art trying to get them right!

Also, you'll need some way to program the nRF52 module via the SWD pins.

I'm going to close this bug though because I'm not posting BOMs for the boards I produce. It's just a step too far - I'll get complaints if someone wastes money on the wrong thing, and I've already had a several people add all the part costs together and then try and beat me down on price with the threat of making the boards themselves :(

**Comment by robksawyer** [comment]
@gfwilliams I totally understand. Thanks for the feedback and the info you were able to provide. This is great for the open hardware community and it's unfortunate that feedback like the following is happening. 

> ... I've already had a several people add all the part costs together and then try and beat me down on price with the threat of making the boards themselves ...

They're definitely forgetting all of the time and labor that went into the dreaming and prototyping phases before locking down a final design. Anyway, nice work on the project and end product. I'm looking forward to learning more and using it.

**Comment by gfwilliams** [comment]
No problem - hope it works well for you! Apart from the inductors/capacitors there's not much you need to get something working.

> and it's unfortunate that feedback like the following is happening.

Yes, but it always seems to be the way. Luckily the people that see Open Source as something to exploit are made up for by the ones that help to contribute back :)
